# -*- coding: utf-8 -*-
"""function_errors

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YhGh7nGBKqfx1KlPY-ziJWxY7Gonuk-1
"""

def failed_startups_india():
  print ("Byju's - Aggressive acquisitions, unsustainable debt, and governance disputes")
  print ("Dunzo - High operational cash burn and fierce competition from Blinkit, Zepto, and Swiggy Instamart")
  print ("Koo - High infrastructure costs and inability to monetize or secure fresh funding runway.")
  print ("Go Mechanic - Financial misreporting and accounting irregularities that led to an investor pullout.")
  print ("Stayzilla - Financial misreporting and accounting irregularities that led to an investor pullout.")
  print ("Peppertap - Extreme discounting, reverse logistics costs, and negative unit economics.")

failed_startups_india()

def anatomy_of_byjus_downfall(Byjus_Collapse_Reasons):
  print ("Unpayable debt: Defaulted on a massive $1.2 billion overseas loan")
  print ("Aggressive acquisitions: Burned billions buying companies without sustainable operational integration")
  print ("Governance collapse: Board resignations, auditor exits, and extreme sales misconduct")

anatomy_of_byjus_downfall("Why did Byjus fail?")

anatomy_of_byjus_downfall("What are the 3 reasons for the Byjus downfall?")

anatomy_of_byjus_downfall ("The downfall journey of Byjus")

def dwarka_travel_expenses (hotel,travel, other, food):
  return hotel + food + travel + other
print('Dwarka Travel Expenses:', dwarka_travel_expenses(23000, 10000, 6500, 4900))

def dwarka_travel_expenses (hotel, travel, other,food):
  return (hotel + other + travel) - food
print('Dwarka Travel Expenses:', dwarka_travel_expenses(23000, 10000, 6500, 4900))

def dwarka_travel_expenses (hotel, food, travel, other):
  return (hotel+other) - (travel + food)
print ('Dwarka Travel Expenses:', dwarka_travel_expenses(23000, 10000, 6500, 4900))

def dwarka_travel_expenses(hotel, food, travel, other):
  return (hotel + travel + other+food)/2
print ('Dwarka Travel Expenses:', round(dwarka_travel_expenses(23000, 10000, 6500, 4900),2))

def dwarka_travel_expenses(hotel, travel, other,food=2000):
  return (hotel+travel+other+food) / 2
print ('Dwarka Travel Expenses:', round (dwarka_travel_expenses(23000, 10000, 6500),2))

def expenses(*args):
    print(args)

expenses(1000, 2000, 3000)

def income(*args):
    total = sum(args)
    print(total)

income(2000, 4000, 6000)

def expenses(*args):
  total = sum(args)*2
  print (total)

expenses(12000, 50000, 3400/2,-1000)

def expenses(**kwargs):
    total = sum(kwargs.values()) * 2
    print(total)

expenses(hotel=1200, food=1600, other=1900)

def expenses(hotel, food=500, *args, **kwargs):
    print(hotel)
    print(food)
    print(args)
    print(kwargs)
expenses(
    2000,
    800,
    1000,
    1500,
    travel=3000,
    other=700
)

def expenses (hotel, food=500, *args, **kwargs):
  print(hotel)
  print (food)
  print (args)
  print (kwargs)
expenses(
    2000,
    800,
    1000,
    1500,
    travel = 3000,
    other = 700
)

def total_marks (maths, physics, chemistry):
  total_marks = maths+physics+chemistry
  average = total_marks/3

  return total_marks, average

values = total_marks (89,90,91)

print (values)

def calculate ():
  total = (1500 + 2300) - 1200
  print (total)
calculate ()

total = (1500 + 3400)/2

def calculate ():
  global total
  total = 1000
  print (total)
calculate ()
print ()

total = (2800*2)

def analysis ():
  global total
  print (total)
analysis ()
print ()

def calculate_total(price, quantity):
    return price * quantity

def display_bill ():
    total = calculate_total(500,3)
    print (total)

display_bill()

def calculate_total(price, quantity):
    return price * quantity


def display_bill():
    total = calculate_total(500/2, 3)
    print(total)


display_bill()

def total_education_amount (school, college, university):
    return school + college + university

def education_expenses():
    total = total_education_amount (300000, 400000, 700000)
    print (total)

education_expenses()

file = open ('guests.txt', 'r')
data = file.read()
print (data)
file.close ()

file = open ('guests.txt', 'r')
data = file.read()
print (data)
file.close()

with open ('guests.txt', 'r') as file:
  data = file.read()
  print (data)

with open ('guests.txt', 'r'):
  data = file.read()
  print (data)

try:
  with open ('guests.txt', 'r') as file:
    data = file.read()
    print (data)
except FileNotFoundError:
  print ("The file was not found")

try:
   (20 + 30 + 90 = 100)
except Calculation is wrong:
  print ('Calculation is wrong')

try:
    result = 0 / 0

except ZeroDivisionError:
    print("You cannot divide by zero.")

numbers = 12
print (numbers)

numbers = int("hello")

try:
  age =int(input('Enter your age:'))
  print (age)
except ValueError:
  print ("Please enter a valid number")

expenses_distribution = 350/0

try:
  number = 350
  result = number / 0
  print (result)
except ZeroDivisionError:
  print ('You cannot divide by zero')

number = 350
name = 'rahul'
result = number + name

try:
  number = 350
  name = 'rahul'
  result = number + name
  print (result)
except TypeError:
  print ('You cannot add an interger to string')

numbers = [100, 200, 300, 400, 600, 900]
print (numbers[90])

try:
  numbers = [100, 200, 300, 400, 600, 900]
  print (numbers[19])
except IndexError:
  print ('Index is out of range')

rank_details = {
    '1st_rank' : 'Dev',
    '2nd_rank' : 'Radha',
    '3rd_rank' : 'Rukmini'
}

print (rank_details['Krishna'])

try:
  rank_details = {
    '1st_rank' : 'Dev',
    '2nd_rank' : 'Radha',
    '3rd_rank' : 'Rukmini'
}

  print (rank_details['Krishna'])

except KeyError:
  print ('Key is out of range')

names = ['Radha', Rukmini, 'Krishna', 'Balaram', 'Vasudheva']
print (Rukmini)

try:
  names = ['Radha', 'Rukmini', 'Krishna', 'Balaram', 'Vasudheva']
  print (Ram)
except NameError:
  print ('Variable does not exist')

file = open ('ram.txt')

try:
  file = open('student.txt')
  print (file.read())
except FileNotFoundError:
  print ('File does not exist')

insults = (23, 67, 89, 13, 15,19)
insults.append(20)
print (insults)

try:
  insults = (23, 67, 89, 13, 15,19)
  insults.append(20)
  print (insults)
except AttributeError:
  print ('This list has no such attribute')

bad_boys = ['alpha', 'beta', 'gama', 'trigo']
scores = [23, 24, 21, 23]
total = 0
for score in scores
  total_scores = total + scores
  total =   total_scores
  print (total)

try:
  bad_boys = ['alpha', 'beta', 'gama', 'trigo']
  scores = [23, 24, 21, 23]
  total = 0
for score in scores

except IndentationError:
  print (Expected':')

try:
  number = int(input("Enter a number:"))
  output = 10*number
  print (output)
except ValueError:
  print ("Please enter a valid number")
except ZeroDivisionError:
  print ('You cannot divide by zero')
else:
  print ('Mahabharatam:', output)
finally:
  print ('Ram go to Pendekal')

try:
  age =ram

  if age <0:
    raise ValueError('Age cannot be negative')
except ValueError:
  print ('Invalid Age')

try:
    age = -5

    if age < 0:
        raise ValueError("Age cannot be negative")

except ValueError:
    print("Invalid age")

try:
    age = int(input("Enter your age: "))

    if age < 0:
        raise ValueError("Age cannot be negative")

    print("Your age is:", age)

except ValueError:
    print("Invalid age")

class InvalidMarksError(Exception):
    pass

class goodboy(Exception):
  pass

class badboys(Exception):
  pass

try:
    age = int(input("Enter your age: "))

    if age < 0:
        raise badboys("Age cannot be negative")

    print("Your age is:", age)

except badboys:
    print("Invalid age")

file=open('data.txt', 'w')
file.write('Hello Python')
file.close()

file=open('data.txt', 'a')
file.write('\n Hell0 Python')
file.write ('Ram is very strategic person')
file.close()

file = open('data.txt', 'r')
lines = file.readlines()
print (lines)
file.close()

file=open ('data.txt', 'r')
lines = file.readlines()
print (lines)
file.close ()

with open ('data.txt','r') as file:
  content = file.read()
  print (content)

try:
  with open('data.txt','r') as file:
    content = file.read()
    print (content)
except [FileNotFoundError]:
    print ('File Does not found')

with open ('student.txt', 'w') as file:
  file.write ('Rahul\n')
  file.write ('Priya\n')
  file.write ('Amit\n')

with open ('student.txt', 'a') as file:
  file.write('sneha\n')

